name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Unzip legacy source
        run: unzip -qq 'simiriki-e768af42-main (extract.me).zip' -d .

      - name: Move extracted contents
        run: |
          mv 'simiriki-e768af42-main'/* ./
          mv 'simiriki-e768af42-main'/.* ./ || true

      - name: Clean up
        run: |
          rm -rf 'simiriki-e768af42-main' 'simiriki-e768af42-main (extract.me).zip'

      # Build & Deploy to Azure Static Web Apps
      - name: Build and Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"  # adjust if needed
          output_location: "build"  # adjust if needed
